---
# tasks file for mailfruit
- name: Install base
  ansible.builtin.include_tasks:
    file: base.yml

- name: Use certbot to install certs
  ansible.builtin.include_tasks:
    file: certbot.yml

- name: Install opendkim
  ansible.builtin.include_tasks:
    file: opendkim.yml

- name: Install postfix
  ansible.builtin.include_tasks:
    file: postfix.yml

- name: Install dovecot
  ansible.builtin.include_tasks:
    file: dovecot.yml

- name: Install trees
  ansible.builtin.include_tasks:
    file: trees.yml

- name: Install user database
  ansible.builtin.include_tasks:
    file: user_database.yml
