---
# This play should occur before Postfix.
- name: Install opendkim
  ansible.builtin.apt:
    name:
    - opendkim
    - opendkim-tools
    state: present

- name: Manage /etc/opendkim/keys
  ansible.builtin.file:
    path: /etc/opendkim/keys
    state: directory
    owner: root
    group: opendkim
    mode: '0750'

- name: Make opendkim key
  ansible.builtin.command: "opendkim-genkey -s {{ mailfruit_dkim_selector }}"
  args:
    chdir: /etc/opendkim/keys
    creates: "/etc/opendkim/keys/{{ mailfruit_dkim_selector }}.private"

- name: Set dkim key permissions
  ansible.builtin.file:
    path: /etc/opendkim/keys
    state: directory
    owner: root
    group: opendkim
    mode: '0750'
    recurse: yes

- name: Modify /etc/default/opendkim
  ansible.builtin.lineinfile:
    path: /etc/default/opendkim
    regexp: '^SOCKET='
    line: 'SOCKET="inet:12301@127.0.0.1"'
  notify:
    - Restart opendkim

- name: Manage /etc/opendkim.conf
  ansible.builtin.template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: '0755'
  notify:
    - Restart opendkim
