name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  basic:
    runs-on: debian-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - debian-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Lint with yamllint
        run: yamllint defaults handlers meta tasks templates tests
      - name: Lint with ansible-lint
        run: ansible-lint .
